import {measurementHTML} from './growth-measurement.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>v==null?'—':Number(v).toLocaleString('en-GB',{maximumFractionDigits:2});
const link=url=>{try{const u=new URL(url);return u.protocol==='https:'&&u.hostname==='brainilabgames.com'?`<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(u.pathname)} ↗</a>`:esc(url);}catch{return esc(url);}};
export function connectionText(report,now=Date.now()){
 const c=report?.connection,t=Date.parse(c?.lastSuccessfulSync);
 if(c?.status!=='verified'||c.scope!=='https://www.googleapis.com/auth/webmasters.readonly'||!Number.isFinite(t))return 'No verified Google connection in this report. Manual import is available.';
 return `${now-t>48*3600000?'Last verified sync is more than 48 hours old.':'Google read-only connection verified.'} Last successful sync: ${new Date(t).toLocaleString('en-GB')}. Scheduling is managed on the private computer; this timestamp confirms a completed sync, not a future run.`;
}
export function briefText(lead,report){
 return [`# ${lead.name}`,`Page: ${lead.url}`,`Evidence period: ${report.availablePeriod.start} to ${report.availablePeriod.end}`,`Snapshot: ${lead.pageSourceSnapshot}`,'',lead.brief.finding,'',`Action: ${lead.action}`,'','## Observed queries for this exact page',...(lead.queryEvidence||[]).map(q=>`- ${q.value}: ${q.impressions} impressions, ${q.clicks} clicks`),'','## Editorial review',...lead.brief.checks.map(c=>`- [ ] ${c}`),'',`Outcome to measure: ${lead.conversionGoal}`,'No forecast or causal claim. Recheck the live page and sources before editing.'].join('\n');
}
export function toolsHTML(r){
 if(!r)return '';
 const leads=r.discovery||[],h=r.health;
 return `<section class="growth-research" aria-labelledby="growth-research-heading"><div class="growth-toolbar"><div><p class="admin-eyebrow">Discover → write → measure</p><h2 id="growth-research-heading">Your next useful improvement</h2></div><label>Find a page or query<input type="search" data-research-filter placeholder="Search opportunities"/></label></div><p class="growth-small">These leads use at least 10 observed impressions. The 3% CTR and position 20 cutoffs help sort the work; they are not benchmarks or forecasts.</p><div class="growth-discovery">${leads.map((o,i)=>`<article class="growth-lead-card" data-lead="${i}"><p class="admin-eyebrow">${esc(o.kind)} · ${esc(o.action)}</p><h3>${esc(o.name)}</h3>${link(o.url)}<dl class="growth-evidence"><div><dt>Impressions</dt><dd>${num(o.pageEvidence.impressions)}</dd></div><div><dt>Clicks</dt><dd>${num(o.pageEvidence.clicks)}</dd></div><div><dt>Avg. position</dt><dd>${num(o.pageEvidence.position)}</dd></div></dl><details><summary>Open the editorial brief</summary><p>${esc(o.brief.finding)}</p>${o.queryEvidence.length?`<ul>${o.queryEvidence.map(q=>`<li><strong>${esc(q.value)}</strong> · ${num(q.impressions)} impressions</li>`).join('')}</ul>`:'<p>No visible query/page pairs. Research intent before choosing a keyword.</p>'}<ol>${o.brief.checks.map(c=>`<li>${esc(c)}</li>`).join('')}</ol><button type="button" class="admin-button" data-export-brief="${i}">Download brief</button></details></article>`).join('')}</div><p data-research-empty ${leads.length?'hidden':''}>No matching leads in this report. This is not proof of no search demand.</p></section><div class="growth-tools-grid"><section class="admin-panel"><p class="admin-eyebrow">Site health</p><h2>What needs checking?</h2>${h?`<p>${num(h.checkedPages)} pages checked · ${num(h.issues.length)} pages flagged</p><p class="growth-small">Audit: ${esc(h.checkedAt||'Date not supplied')}. ${esc(h.scope)}</p><details><summary>Inspect findings</summary>${h.issues.length?`<ul>${h.issues.map(p=>`<li>${link(p.url)}<p>${esc(p.checks.join(' · '))}</p></li>`).join('')}</ul>`:'<p>No issues found by these limited checks.</p>'}</details>`:'<p>No public audit attached yet.</p>'}</section>${measurementHTML(r)}</div>`;
}
export function bindTools(root,report){
 const input=root.querySelector('[data-research-filter]');if(!input)return;
 input.oninput=()=>{let count=0;const value=input.value.trim().toLowerCase();root.querySelectorAll('[data-lead]').forEach(el=>{const lead=report.discovery[Number(el.dataset.lead)];el.hidden=!JSON.stringify([lead.name,lead.url,lead.queryEvidence.map(q=>q.value)]).toLowerCase().includes(value);if(!el.hidden)count++;});root.querySelector('[data-research-empty]').hidden=count>0;};
 root.querySelectorAll('[data-export-brief]').forEach(button=>button.onclick=()=>{const lead=report.discovery[Number(button.dataset.exportBrief)];const url=URL.createObjectURL(new Blob([briefText(lead,report)],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='brainilab-editorial-brief.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
}
