// OpenSEO evidence lives in the existing private Growth report, behind admin RPCs.
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>Number.isFinite(Date.parse(v))?new Date(v).toLocaleString('en-GB'):'Not recorded';
const number=v=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('en-GB'):'Unknown';
const workflows=[['seo-project-setup','Project context','Keep our audience, goals and writing preferences together.'],['seo-audit','Site audit','Find what stops useful pages being discovered or understood.'],['keyword-research','Keyword opportunities','Match real search demand to games, articles and Academy.']];
const states={queued:'Waiting to run',running:'In progress',blocked:'Action needed',failed:'Last attempt failed',completed:'Completed'};
export function evidenceLink(value,label){
 try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.search)return esc(label);return `<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;}catch{return esc(label);}
}
export function workflowPrompt(id){
 if(!workflows.some(([key])=>key===id))return '';
 return `Run openseo:${id} for brainilabgames.com and return reviewed evidence to BrainiLab Growth.\n\nVerify OpenSEO with whoami and list_projects. Match the existing project by domain and read its context and research log before writing or spending credits. Reuse research less than 30 days old for discovery; verify live rankings for recommendations. Do not create a duplicate project.\n\nThe goal is useful organic traffic that leads to played games, returning users and potential BrainiLab+ customers. Use the owner's established editorial preferences. Do not invent demand, authority, conversion rates or revenue. Preserve existing context and human edits.\n\nFollow tools/growth/OPENSEO.md in the BrainiLab repository. Save dated source references, country, language, limitations and provider estimates separately from Search Console observations. Record results using tools/growth/openseo.py record with the previous snapshot hash, then refresh the Growth report and import it through the existing private workflow. Never copy tokens or account details into the report. A queued task is not a completed analysis. Do not buy subscriptions or credits.`;
}
export function openSEOHTML(report){
 const data=report?.openseo,known=new Map((data?.workflows||[]).map(w=>[w.id,w]));
 const status=data?.connection?.status;
 const connected=status==='verified'&&['whoami','list_projects'].every(k=>data?.connection?.checks?.[k]?.reference);
 return `<section class="growth-openseo" aria-labelledby="growth-openseo-title"><header class="growth-toolbar"><div><p class="admin-eyebrow">Research with OpenSEO</p><h2 id="growth-openseo-title">From questions to a clear next step</h2></div><span class="growth-state" data-state="${connected?'monitoring':'pending'}">${connected?'Verified in saved report':'Tool access not verified'}</span></header><p>${esc(data?.connection?.message||'The OpenSEO workflows are ready to receive results. No completed analysis has been imported yet.')}</p><p class="growth-small">Last access check: ${date(data?.checkedAt)}. This page does not connect to OpenSEO or store its credentials. The Codex cycle runs the research and imports the evidence.</p><ol class="growth-workflow-list">${workflows.map(([id,title,description],index)=>{
 const w=known.get(id),state=states[w?.state]?w.state:'queued',success=w?.lastSuccess;
 return `<li><span class="growth-workflow-number" aria-hidden="true">${index+1}</span><div><div class="growth-workflow-heading"><h3>${title}</h3><span class="growth-state" data-state="${state==='completed'?'monitoring':'pending'}">${states[state]}</span></div><p>${description}</p>${w?.note?`<p class="growth-small">${esc(w.note)}</p>`:''}${success?`<p class="growth-small">Last successful result: ${date(success.at)}</p><p>${esc(success.summary)}</p>${success.reportUrl?evidenceLink(success.reportUrl,'Open saved report ↗'):''}`:'<p class="growth-small">No verified result yet.</p>'}<details><summary>Open Codex task</summary><p>This downloads a task brief. Downloading does not start research or publish a change.</p><button type="button" class="admin-button" data-openseo-brief="${id}">Download ${title.toLowerCase()} task</button></details></div></li>`;
 }).join('')}</ol><details><summary>OpenSEO findings (${data?.opportunities?.length||0})</summary>${data?.opportunities?.length?`<div class="growth-table"><table><caption>Provider estimates, separate from observed Search Console traffic</caption><thead><tr><th scope="col">Topic and page</th><th scope="col">Market and date</th><th scope="col">Estimated monthly searches</th><th scope="col">Recommended action</th></tr></thead><tbody>${data.opportunities.map(o=>`<tr><th scope="row">${esc(o.keyword)}<br>${evidenceLink(o.url,'Open page ↗')}</th><td>${esc(o.country)} · ${esc(o.language)}<br>${date(o.observedAt)}</td><td>${number(o.estimatedMonthlySearches)}</td><td>${esc(o.action)}<details><summary>Evidence and limits</summary><p>${esc(o.finding)}</p><p>${esc(o.limitations)}</p><ul>${(o.sources||[]).map(s=>`<li>${evidenceLink(s,s)}</li>`).join('')}</ul></details></td></tr>`).join('')}</tbody></table></div>`:'<p>No OpenSEO findings imported. This does not mean there are no opportunities.</p>'}</details><p class="growth-small">Reviewed findings join the same decision queue. Growth keeps one decision per page, retains its original baseline and checks the live page before acting. New articles keep the existing editorial cadence.</p></section>`;
}
export function bindOpenSEO(root){
 root.querySelectorAll('[data-openseo-brief]').forEach(button=>button.onclick=()=>{
  const id=button.dataset.openseoBrief,body=workflowPrompt(id);if(!body)return;
  const objectURL=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'}));
  const a=document.createElement('a');a.href=objectURL;a.download=`brainilab-openseo-${id}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(objectURL),1000);
 });
}
