import {newTabLinks} from './link-policy.js';
import {esc,cleanHtml,safeCover,safeLink,BASE} from './learn-content.js';
import {organization,personSchema,articleByline} from './learn-seo.js';
import {validQuiz,readyPaths} from './learning-model.js';
const json=v=>JSON.stringify(v).replace(/</g,'\\u003c');
export const learningAssets='<link rel="stylesheet" href="/assets/css/learning-paths.css?v=7"/><script defer src="/assets/js/learning-paths.bundle.js?v=7"></script>';
export function enrichAuthors(articles,authors){return articles.map(a=>({...a,author:authors.find(p=>p.slug===a.authorId)||a.author}));}
export function pathData(path,articles){return path.lessons.map(l=>({slug:l.slug,version:articles.find(a=>a.slug===l.slug)?.quiz?.version}));}
function progress(p,articles){return `<div class="path-progress" data-path-progress data-lessons="${esc(json(pathData(p,articles)))}"><span data-progress-label>0 of ${p.lessons.length} lessons completed · 0%</span><progress value="0" max="100" aria-label="${esc(p.title)} completion"></progress></div>`;}
export function academyCard(p,articles){
 const first=articles.find(a=>a.slug===p.lessons[0].slug),cover=articles.find(a=>a.slug===p.coverArticle)?.cover||first.cover;
 return `<article class="learn-card academy-card" data-format="academy" data-topic="${esc(p.topic)}" data-latest-topic><div class="learn-card-art"><img src="${esc(cover.small||cover.src)}" alt="${esc(cover.alt)}" width="480" height="320" loading="lazy" decoding="async"/></div><div class="learn-card-copy"><p class="learn-format-label">Academy</p><p class="eyebrow">${esc(p.topic)} <span>· ${p.lessons.length} lessons</span></p><h3><a href="/learn/paths/${p.slug}/">${esc(p.title)}</a></h3><p>${esc(p.description)}</p>${progress(p,articles)}<a class="path-continue" href="/learn/${first.slug}/" data-continue data-lessons="${esc(json(pathData(p,articles)))}">Start learning →</a></div></article>`;
}
export function chapterMenu(p,articles,current=''){
 return `<nav class="academy-outline" aria-label="Course chapters"><p class="eyebrow">BrainiLab Academy</p><a class="outline-title" href="/learn/paths/${p.slug}/">${esc(p.title)}</a><details open data-chapter-menu><summary>Chapters · ${p.lessons.length} lessons</summary><ol>${p.lessons.map((l,i)=>{const a=articles.find(a=>a.slug===l.slug);return `<li data-lesson="${a.slug}" data-version="${esc(a.quiz.version)}"><a href="/learn/${a.slug}/"${a.slug===current?' aria-current="page"':''}><span class="lesson-number" data-lesson-number="${i+1}">${i+1}</span><span>${esc(a.title)}</span></a><span class="outline-status" data-lesson-status>Ready when you are</span></li>`;}).join('')}</ol>${progress(p,articles)}</details></nav>`;
}
export function pathsSection(paths,articles,full=false){
 const available=readyPaths(paths,articles);
 return `<section class="learning-paths" id="learning-paths"><div class="section-heading"><div><p class="eyebrow">Read · try · build on it</p><h${full?'1':'2'}>BrainiLab Academy</h${full?'1':'2'}></div>${full?'<a href="/learn/">Browse articles →</a>':'<a href="/learn/paths/">Explore the Academy →</a>'}</div><p>Start with the essentials, then connect the ideas. Each short lesson ends with a quick four-option round.</p><p><a href="/reasoning/">Try the Reasoning Challenge · 12 puzzles, no timer →</a></p><p class="path-storage-note" data-progress-storage>Finish a quick quiz to tick off a chapter. Your progress is saved as you go.</p><div class="path-grid">${available.map(p=>{const first=articles.find(a=>a.slug===p.lessons[0].slug),cover=articles.find(a=>a.slug===p.coverArticle)?.cover||first.cover;return `<article class="path-card"><img src="${esc(cover.small||cover.src)}" alt="${esc(cover.alt)}" width="480" height="320" loading="lazy"/><div><p class="eyebrow">${esc(p.topic)} · ${p.lessons.length} lessons</p><h${full?'2':'3'}><a href="/learn/paths/${p.slug}/">${esc(p.title)}</a></h${full?'2':'3'}><p>${esc(p.description)}</p>${progress(p,articles)}<a class="path-continue" href="/learn/${first.slug}/" data-continue data-lessons="${esc(json(pathData(p,articles)))}">Start learning →</a></div></article>`;}).join('')||'<p>New Academy courses are being prepared. <a href="/learn/">Explore the articles</a> while we put the lessons together.</p>'}</div></section>`;
}
export function pathBody(p,articles,authors){
 const author=authors.find(a=>a.slug===p.authorId),first=articles.find(a=>a.slug===p.lessons[0].slug),cover=articles.find(a=>a.slug===p.coverArticle)?.cover||first.cover;
 return `<div class="wrap academy-course"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/learn/">Learn</a><span>/</span><a href="/learn/paths/">BrainiLab Academy</a></nav><div class="academy-layout"><aside class="academy-sidebar">${chapterMenu(p,articles)}</aside><div class="academy-main"><header class="academy-hero"><div class="academy-hero-copy"><p class="eyebrow">BrainiLab Academy · ${esc(p.topic)}</p><h1>${esc(p.title)}</h1><p>${esc(p.description)}</p>${articleByline({...p,author})}<p class="academy-course-meta">${p.lessons.length} short reads · A quick quiz after each one</p></div><img src="${esc(cover.src)}" alt="${esc(cover.alt)}" width="960" height="640" fetchpriority="high"/></header><div class="path-overview"><div><h2>A little curiosity goes a long way.</h2>${cleanHtml(p.introduction)}</div><aside><h2>Your progress</h2>${progress(p,articles)}<p data-progress-storage>Saved on this browser. Finish each lesson’s round to add a tick. You can revisit any lesson.</p><a href="/learn/${p.lessons[0].slug}/" class="btn" data-continue data-lessons="${esc(json(pathData(p,articles)))}">Start learning →</a></aside></div><div class="academy-lessons-heading"><p class="eyebrow">One discovery at a time</p><h2>Start here. See where it takes you.</h2></div><ol class="path-lessons">${p.lessons.map((l,i)=>{const a=articles.find(a=>a.slug===l.slug);return `<li data-lesson="${a.slug}" data-version="${esc(a.quiz.version)}"><span class="lesson-number" data-lesson-number="${i+1}" aria-label="Lesson ${i+1}">${i+1}</span><img class="lesson-photo" src="${esc(a.cover.small||a.cover.src)}" alt="" width="240" height="160" loading="lazy"/><div class="lesson-copy"><p class="eyebrow">${a.minutes} min read · Quick quiz</p><h3><a href="/learn/${a.slug}/">${esc(a.title)}</a></h3><p>${esc(l.objective)}</p><span data-lesson-status>Ready when you are</span></div><a href="/learn/${a.slug}/" aria-label="Read ${esc(a.title)}">Read →</a></li>`;}).join('')}</ol>${p.glossary?.length?`<section class="path-glossary"><h2>A few words worth knowing</h2><dl>${p.glossary.map(g=>`<dt>${esc(g.term)}</dt><dd>${esc(g.definition)}</dd>`).join('')}</dl></section>`:''}<section class="academy-sources"><h2>Curious to dig deeper?</h2><ul>${(p.sources||[]).filter(s=>safeLink(s.url)).map(s=>`<li><a href="${esc(s.url)}">${esc(s.name)}</a></li>`).join('')}</ul><p>Follow the sources, explore a little further, or tell us if something needs a correction. <a href="/suggestions/">Suggest a correction</a>.</p></section><p><a href="/learn/paths/">Explore another Academy course →</a></p></div></div></div>`;
}
export function lessonExtras(a,paths,articles){
 const memberships=readyPaths(paths,articles).filter(p=>p.lessons.some(l=>l.slug===a.slug));
 const nav=memberships.map(p=>{const i=p.lessons.findIndex(l=>l.slug===a.slug);return `<nav class="lesson-route" aria-label="${esc(p.title)}"><p><a href="/learn/paths/${p.slug}/">${esc(p.title)}</a> · Lesson ${i+1} of ${p.lessons.length}</p>${progress(p,articles)}<div>${i?`<a href="/learn/${p.lessons[i-1].slug}/">← Previous lesson</a>`:'<span>Start here</span>'}${i+1<p.lessons.length?`<a href="/learn/${p.lessons[i+1].slug}/">Next lesson →</a>`:`<a href="/learn/paths/${p.slug}/">Review your path →</a>`}</div></nav>`;}).join('');
 const sidebar=memberships.map(p=>chapterMenu(p,articles,a.slug)).join('');
 if(!validQuiz(a.quiz))return {nav,sidebar,quiz:''};
 const followCourses={'maths-from-zero':'fractions-from-zero','fractions-from-zero':'mental-maths-foundations'};
 const completion=memberships.map(p=>{const follow=readyPaths(paths,articles).find(other=>other.slug===followCourses[p.slug]);const lessons=pathData(p,articles).map(l=>({...l,title:articles.find(a=>a.slug===l.slug).title}));return `<div data-completion-route data-course="/learn/paths/${p.slug}/" data-lessons="${esc(json(lessons))}"><h3>${esc(p.title)}</h3><p data-completion-progress></p><progress max="100" value="0" aria-label="${esc(p.title)} completion"></progress><a class="btn" data-completion-next href="/learn/paths/${p.slug}/">Continue learning</a>${follow?`<a class="completion-follow" data-follow-course hidden href="/learn/paths/${follow.slug}/">Ready for another idea? ${esc(follow.title)} →</a>`:''}</div>`;}).join('');
 const quiz=`<section class="lesson-quiz academy-quiz" id="quick-round" data-quiz-slug="${a.slug}"><div class="academy-quiz-heading"><img src="/assets/icons/games/standard/brain-mix.svg" alt="" width="44" height="44"/><div><p>BrainiLab Academy</p><h2>Ready to try it?</h2></div><span class="academy-xp-badge">40 XP</span></div><p>${a.quiz.questions.length} quick questions. Take your time and learn from each answer.</p><p class="academy-reward-note">Complete this lesson to earn 40 account XP once. Academy does not add ranking points. Sign in to collect XP.</p><noscript><p>Enable JavaScript to play this round and save progress.</p></noscript><form data-lesson-quiz hidden><div class="academy-round-meta"><span data-question-counter>Question 1 of ${a.quiz.questions.length}</span><span>No timer. Just curiosity.</span></div><progress class="academy-round-progress" data-round-progress max="${a.quiz.questions.length}" value="0" aria-label="Questions answered"></progress>${a.quiz.questions.map((q,i)=>`<fieldset data-question="${i}"${i?' hidden':''}><legend tabindex="-1">${esc(q.prompt)}</legend><div class="answers">${q.options.map((o,j)=>`<label class="answer"><input type="radio" name="question-${i}" value="${j}"${i?' disabled':''} required/><span class="key">${'ABCD'[j]}</span><span>${esc(o)}</span></label>`).join('')}</div><p class="quiz-explanation" data-explanation="${i}" role="status" hidden></p></fieldset>`).join('')}<div class="academy-quiz-actions"><button class="btn" type="submit">Check answer</button><button class="btn" type="button" data-quiz-next hidden>Next question →</button><button class="btn-light" type="button" data-quiz-retry hidden>Practise again</button></div></form><section class="academy-completion" data-completion-panel hidden aria-label="Lesson completed"><div class="completion-heading"><span aria-hidden="true">✓</span><h2>One more idea to take with you.</h2></div><div data-quiz-result role="status" tabindex="-1"></div><p class="completion-xp" data-completion-xp role="status"></p><p class="completion-note">Academy XP builds your account level. Ranking points come from games.</p><button class="btn-light" type="button" data-sync-retry hidden>Retry saving to my account</button>${completion}</section><script type="application/json" data-quiz-data>${json(a.quiz)}</script></section>`;
 return {nav,sidebar,quiz};
}
export function teamSection(authors){
 const people=authors.filter(a=>a.visible&&a.active!==false);
 return `<section class="team-section" id="team" aria-label="The people behind BrainiLab"><div class="about-people">${people.map(a=>`<article class="biel-profile" id="${esc(a.slug)}" aria-labelledby="${esc(a.slug)}-name"><div class="biel-identity">${safeCover(a.photo)?`<img class="person-photo" src="${esc(a.photo)}" alt="${esc(a.name)}" width="160" height="160" decoding="async"/>`:`<div class="biel-monogram" aria-hidden="true">${esc(a.name.split(/\s+/).map(n=>n[0]).slice(0,2).join(''))}</div>`}<h2 id="${esc(a.slug)}-name">${esc(a.name)}</h2>${a.role?`<p class="biel-role">${esc(a.role)}</p>`:''}${(a.socials||[]).filter(s=>safeLink(s.url)&&s.url.startsWith('https:')).map(s=>`<a class="biel-link" rel="me noopener noreferrer" target="_blank" href="${esc(s.url)}">${esc(s.name)} <span aria-hidden="true">↗</span></a>`).join('')}</div><div class="biel-copy">${(a.biography||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('')}<nav class="biel-explore" aria-label="Explore BrainiLab"><a href="/learn/paths/">Explore Academy →</a><a href="/learn/">Read something new →</a></nav></div></article>`).join('')}</div></section>`;
}
export function renderLearningPage(template,{paths=[],articles=[],authors=[],path=null}){
 template=template.replace(/<link rel="stylesheet" href="\/assets\/css\/learning-paths\.css[^"]*"\/>/g,'').replace(/<script defer src="\/assets\/js\/learning-paths\.bundle\.js[^"]*"><\/script>/g,'').replace(/<meta name="twitter:(?:title|description|image|image:alt)"[^>]*>/g,'');
 const url=BASE+'/learn/paths/'+(path?path.slug+'/':''),title=path?.title||'BrainiLab Academy',description=path?.description||'Build your understanding with short, ordered lessons and quick practice rounds.';
 const body=path?pathBody(path,articles,authors):`<div class="wrap">${pathsSection(paths,articles,true)}</div>`;
 const schema={'@context':'https://schema.org','@graph':[organization,{'@type':path?'LearningResource':'CollectionPage','@id':url,url,name:title,description,inLanguage:'en',isAccessibleForFree:true,...(path?{learningResourceType:'Learning path',educationalLevel:'Beginner',author:personSchema(authors.find(a=>a.slug===path.authorId)),hasPart:path.lessons.map((l,i)=>({'@type':'LearningResource',position:i+1,name:articles.find(a=>a.slug===l.slug).title,url:BASE+'/learn/'+l.slug+'/'})),citation:path.sources.map(s=>s.url)}:{hasPart:paths.map(p=>({'@type':'LearningResource',name:p.title,url:BASE+'/learn/paths/'+p.slug+'/'}))})},{'@type':'BreadcrumbList',itemListElement:[{name:'Learn',item:BASE+'/learn/'},{name:'BrainiLab Academy',item:BASE+'/learn/paths/'},...(path?[{name:title,item:url}]:[])].map((v,i)=>({'@type':'ListItem',position:i+1,...v}))}]};
 return newTabLinks(template.replace(/<main id="main-content">[\s\S]*?<\/main>/,()=>`<main id="main-content">${body}</main>`).replace(/<title>[\s\S]*?<\/title>/,()=>`<title>${esc(title)} | BrainiLab</title>`).replace(/<meta name="description"[^>]*>/,()=>`<meta name="description" content="${esc(description)}"/>`).replace(/<link rel="canonical"[^>]*>/,`<link rel="canonical" href="${url}"/>`).replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/,()=>`<script type="application/ld+json">${json(schema)}</script>`).replace(/<script defer src="\/assets\/js\/learn-library[^>]*><\/script>/,'').replace(/<meta property="og:(title|description|url|type)"[^>]*>/g,(_,key)=>`<meta property="og:${key}" content="${esc({title,description,url,type:'website'}[key])}"/>`).replace('</head>',learningAssets+'</head>'));
}
