import {esc,cleanHtml,safeCover,safeLink,BASE} from './learn-content.js';
import {organization,personSchema,articleByline} from './learn-seo.js';
import {validQuiz,readyPaths} from './learning-model.js';
const json=v=>JSON.stringify(v).replace(/</g,'\\u003c');
export const learningAssets='<link rel="stylesheet" href="/assets/css/learning-paths.css?v=1"/><script defer src="/assets/js/learning-paths.bundle.js?v=1"></script>';
export function enrichAuthors(articles,authors){return articles.map(a=>({...a,author:authors.find(p=>p.slug===a.authorId)||a.author}));}
export function pathData(path,articles){return path.lessons.map(l=>({slug:l.slug,version:articles.find(a=>a.slug===l.slug)?.quiz?.version}));}
function progress(p,articles){return `<div class="path-progress" data-path-progress data-lessons="${esc(json(pathData(p,articles)))}"><span data-progress-label>0 of ${p.lessons.length} lessons completed · 0%</span><progress value="0" max="100" aria-label="${esc(p.title)} completion"></progress></div>`;}
export function pathsSection(paths,articles,full=false){
 const available=readyPaths(paths,articles);
 return `<section class="learning-paths" id="learning-paths"><div class="section-heading"><div><p class="eyebrow">Read · try · build on it</p><h${full?'1':'2'}>Learning paths</h${full?'1':'2'}></div>${full?'<a href="/learn/">Browse articles →</a>':'<a href="/learn/paths/">Explore all paths →</a>'}</div><p>Start with the essentials, then connect the ideas. Each short lesson ends with a quick four-option round.</p><p class="path-storage-note" data-progress-storage>Progress is saved on this browser. Completion counts finished lessons, not a measure of everything you know.</p><div class="path-grid">${available.map(p=>{const first=articles.find(a=>a.slug===p.lessons[0].slug),cover=articles.find(a=>a.slug===p.coverArticle)?.cover||first.cover;return `<article class="path-card"><img src="${esc(cover.small||cover.src)}" alt="${esc(cover.alt)}" width="480" height="320" loading="lazy"/><div><p class="eyebrow">${esc(p.topic)} · ${p.lessons.length} lessons</p><h${full?'2':'3'}><a href="/learn/paths/${p.slug}/">${esc(p.title)}</a></h${full?'2':'3'}><p>${esc(p.description)}</p>${progress(p,articles)}<a class="path-continue" href="/learn/${first.slug}/" data-continue data-lessons="${esc(json(pathData(p,articles)))}">Start learning →</a></div></article>`;}).join('')||'<p>New learning paths are being prepared. <a href="/learn/">Explore the articles</a> while we put the lessons together.</p>'}</div></section>`;
}
export function pathBody(p,articles,authors){
 const author=authors.find(a=>a.slug===p.authorId);
 return `<div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/learn/">Learn</a><span>/</span><a href="/learn/paths/">Learning paths</a></nav><header class="article-header"><p class="eyebrow">${esc(p.topic)} · ${p.lessons.length} lessons</p><h1>${esc(p.title)}</h1><p>${esc(p.description)}</p>${articleByline({...p,author})}</header><div class="path-overview"><div><h2>What you will learn</h2>${cleanHtml(p.introduction)}<p><strong>Before you start:</strong> ${esc(p.prerequisites||'No previous reading required.')}</p><ul>${(p.outcomes||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div><aside><h2>Your progress</h2>${progress(p,articles)}<p data-progress-storage>Saved on this browser. Finish each lesson’s round to add a tick. You can revisit any lesson.</p><a href="/learn/${p.lessons[0].slug}/" class="btn" data-continue data-lessons="${esc(json(pathData(p,articles)))}">Start learning →</a></aside></div><h2>The route, step by step</h2><ol class="path-lessons">${p.lessons.map((l,i)=>{const a=articles.find(a=>a.slug===l.slug);return `<li data-lesson="${a.slug}" data-version="${esc(a.quiz.version)}"><span class="lesson-number" data-lesson-number="${i+1}" aria-label="Lesson ${i+1}">${i+1}</span><div><p class="eyebrow">${esc(l.level||'Lesson '+(i+1))} · ${a.minutes} min read</p><h3><a href="/learn/${a.slug}/">${esc(a.title)}</a></h3><p>${esc(l.objective)}</p><span data-lesson-status>Ready when you are</span></div><a href="/learn/${a.slug}/" aria-label="Read ${esc(a.title)}">Read →</a></li>`;}).join('')}</ol>${p.glossary?.length?`<section class="path-glossary"><h2>Keep these ideas handy</h2><dl>${p.glossary.map(g=>`<dt>${esc(g.term)}</dt><dd>${esc(g.definition)}</dd>`).join('')}</dl></section>`:''}<section><h2>Sources behind this path</h2><ul>${(p.sources||[]).filter(s=>safeLink(s.url)).map(s=>`<li><a href="${esc(s.url)}">${esc(s.name)}</a></li>`).join('')}</ul><p>Each lesson links its own sources and worked examples. <a href="/suggestions/">Suggest a correction</a>.</p></section><p><a href="/learn/paths/">Explore another learning path →</a></p></div>`;
}
export function lessonExtras(a,paths,articles){
 const memberships=readyPaths(paths,articles).filter(p=>p.lessons.some(l=>l.slug===a.slug));
 const nav=memberships.map(p=>{const i=p.lessons.findIndex(l=>l.slug===a.slug);return `<nav class="lesson-route" aria-label="${esc(p.title)}"><p><a href="/learn/paths/${p.slug}/">${esc(p.title)}</a> · Lesson ${i+1} of ${p.lessons.length}</p>${progress(p,articles)}<div>${i?`<a href="/learn/${p.lessons[i-1].slug}/">← Previous lesson</a>`:'<span>Start here</span>'}${i+1<p.lessons.length?`<a href="/learn/${p.lessons[i+1].slug}/">Next lesson →</a>`:`<a href="/learn/paths/${p.slug}/">Review your path →</a>`}</div></nav>`;}).join('');
 if(!validQuiz(a.quiz))return {nav,quiz:''};
 const quiz=`<section class="lesson-quiz" id="quick-round" data-quiz-slug="${a.slug}"><h2>A quick round before you go</h2><p>${a.quiz.questions.length} questions from this article. Choose A, B, C or D, then check the explanations.</p><noscript><p>Enable JavaScript to play this round and save progress.</p></noscript><form data-lesson-quiz hidden>${a.quiz.questions.map((q,i)=>`<fieldset><legend>${i+1}. ${esc(q.prompt)}</legend>${q.options.map((o,j)=>`<label><input type="radio" name="question-${i}" value="${j}" required/><span class="choice-letter">${'ABCD'[j]}</span><span>${esc(o)}</span></label>`).join('')}<p class="quiz-explanation" data-explanation="${i}" hidden></p></fieldset>`).join('')}<button class="btn" type="submit">Check my answers</button><button class="btn-light" type="button" data-quiz-retry hidden>Try again</button></form><div data-quiz-result role="status" tabindex="-1"></div><button class="btn-light" type="button" data-sync-retry hidden>Retry saving to my account</button><script type="application/json" data-quiz-data>${json(a.quiz)}</script></section>`;
 return {nav,quiz};
}
export function teamSection(authors){return `<section class="section team-section" id="team"><div class="wrap"><p class="eyebrow">The people behind BrainiLab</p><h2>About us</h2><p>We make quizzes, short reads and guided learning paths for curious people.</p><div class="team-grid">${authors.filter(a=>a.visible&&a.active!==false).map(a=>`<article class="team-card" id="${esc(a.slug)}">${safeCover(a.photo)?`<img src="${esc(a.photo)}" alt="${esc(a.name)}" width="160" height="160" loading="lazy"/>`:`<div class="person-initials" aria-hidden="true">${esc(a.name.split(/\s+/).map(n=>n[0]).slice(0,2).join(''))}</div>`}<div><h3>${esc(a.name)}</h3>${a.role?`<p class="eyebrow">${esc(a.role)}</p>`:''}${a.biography?`<p class="person-bio">${esc(a.biography)}</p>`:''}${a.socials?.length?`<ul class="person-socials">${a.socials.filter(s=>safeLink(s.url)&&s.url.startsWith('https:')).map(s=>`<li><a rel="me" href="${esc(s.url)}">${esc(s.name)}</a></li>`).join('')}</ul>`:''}</div></article>`).join('')}</div></div></section>`;}
export function renderLearningPage(template,{paths=[],articles=[],authors=[],path=null}){
 template=template.replaceAll(learningAssets,'').replace(/<meta name="twitter:(?:title|description|image|image:alt)"[^>]*>/g,'');
 const url=BASE+'/learn/paths/'+(path?path.slug+'/':''),title=path?.title||'Learning paths',description=path?.description||'Build your understanding with short, ordered lessons and quick practice rounds.';
 const body=path?pathBody(path,articles,authors):`<div class="wrap">${pathsSection(paths,articles,true)}</div>`;
 const schema={'@context':'https://schema.org','@graph':[organization,{'@type':path?'LearningResource':'CollectionPage','@id':url,url,name:title,description,inLanguage:'en',isAccessibleForFree:true,...(path?{learningResourceType:'Learning path',educationalLevel:'Beginner',author:personSchema(authors.find(a=>a.slug===path.authorId)),hasPart:path.lessons.map((l,i)=>({'@type':'LearningResource',position:i+1,name:articles.find(a=>a.slug===l.slug).title,url:BASE+'/learn/'+l.slug+'/'})),citation:path.sources.map(s=>s.url)}:{hasPart:paths.map(p=>({'@type':'LearningResource',name:p.title,url:BASE+'/learn/paths/'+p.slug+'/'}))})},{'@type':'BreadcrumbList',itemListElement:[{name:'Learn',item:BASE+'/learn/'},{name:'Learning paths',item:BASE+'/learn/paths/'},...(path?[{name:title,item:url}]:[])].map((v,i)=>({'@type':'ListItem',position:i+1,...v}))}]};
 return template.replace(/<main id="main-content">[\s\S]*?<\/main>/,()=>`<main id="main-content">${body}</main>`).replace(/<title>[\s\S]*?<\/title>/,()=>`<title>${esc(title)} | BrainiLab</title>`).replace(/<meta name="description"[^>]*>/,()=>`<meta name="description" content="${esc(description)}"/>`).replace(/<link rel="canonical"[^>]*>/,`<link rel="canonical" href="${url}"/>`).replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/,()=>`<script type="application/ld+json">${json(schema)}</script>`).replace(/<script defer src="\/assets\/js\/learn-library[^>]*><\/script>/,'').replace(/<meta property="og:(title|description|url|type)"[^>]*>/g,(_,key)=>`<meta property="og:${key}" content="${esc({title,description,url,type:'website'}[key])}"/>`).replace('</head>',learningAssets+'</head>');
}
