"""Build the static Learn library from reviewed content/articles/*.json files."""
from pathlib import Path
from html import escape
from urllib.parse import urlsplit
import json
from datetime import datetime
import math
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://brainilabgames.com'
MARKER = '<!-- Generated by tools/build-editorial.py; edit content/articles instead. -->'
home = (ROOT/'index.html').read_text(encoding='utf-8')
header = re.search(r'<header\b.*?</header>', home, re.S).group()
header = re.sub(r'(?<![\w/])((?:href|src|srcset)=")(?!(?:/|https:|#))', r'\1/', header)
header = header.replace('<a href="/learn/">', '<a href="/learn/" aria-current="page">')
footer = re.search(r'<footer\b.*?</footer>', home, re.S).group()
footer = re.sub(r'(?<![\w/])((?:href|src|srcset)=")(?!(?:/|https:|#))', r'\1/', footer)
analytics = home.split('<head>', 1)[1].split('<meta charset', 1)[0]

all_articles = [json.loads(p.read_text(encoding='utf-8')) for p in sorted((ROOT/'content/articles').glob('*.json'))]
slugs = set()
for a in all_articles:
    assert re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', a['slug']), 'Invalid slug'
    assert a['slug'] not in slugs, 'Duplicate slug'
    slugs.add(a['slug'])
    assert a['status'] in ('draft', 'published'), 'Invalid status'
articles = sorted([a for a in all_articles if a['status'] == 'published'], key=lambda a:(a.get('order',999),a['slug']))
by_slug = {a['slug']: a for a in articles}
for a in articles:
    for key in ('title', 'description', 'topic', 'sections', 'sources', 'game', 'hub', 'cover', 'practice'):
        assert a.get(key), f"Missing {key} in {a['slug']}"
    cover=a['cover']
    assert cover.get('alt') and cover.get('credit'), f"Missing cover description/credit in {a['slug']}"
    assert cover['src'].startswith('/assets/images/learn/') and '..' not in cover['src'] and cover['src'].endswith('.webp')
    for image in (cover['src'],cover['src'].replace('.webp','-small.webp')):
        assert (ROOT/image.lstrip('/')).is_file(), f'Missing cover: {image}'
    ids = [section['id'] for section in a['sections']]
    assert len(ids) == len(set(ids)) and all(re.fullmatch(r'[a-z0-9-]+', i) for i in ids)
    for link in (a['game'], a['hub']):
        target = ROOT/urlsplit(link['url']).path.strip('/')/'index.html'
        assert target.is_file(), f'Missing destination: {target}'
    words = len(re.sub('<[^>]+>', ' ', ' '.join(s['html'] for s in a['sections'])).split())
    a['minutes'] = max(1, math.ceil(words/200))

def card(a, eager=False):
    return f'''<article class="learn-card" data-topic="{escape(a['topic'], quote=True)}">
      <div class="learn-card-art"><img src="{escape(a['cover']['src'].replace('.webp','-small.webp'))}" alt="{escape(a['cover']['alt'], quote=True)}" width="480" height="320" loading="{'eager' if eager else 'lazy'}" decoding="async"/></div>
      <div class="learn-card-copy"><p class="eyebrow">{escape(a['topic'])} <span>· {a['minutes']} min read</span></p>
      <h3><a href="/learn/{a['slug']}/">{escape(a['title'])}</a></h3>
      <p>{escape(a['description'])}</p><span class="learn-card-label" aria-hidden="true">Read the guide ↗</span></div>
    </article>'''

def page(path, title, description, body, schema, cover=None):
    url = BASE + path
    cover=cover or {'src':'/assets/brand/og-card.png','alt':'BrainiLab quiz and brain games'}
    graph = {'@context': 'https://schema.org', '@graph': [schema, {'@type':'BreadcrumbList','itemListElement':[
        {'@type':'ListItem','position':1,'name':'Home','item':BASE+'/'},
        {'@type':'ListItem','position':2,'name':'Learn','item':BASE+'/learn/'}
    ] + ([] if path == '/learn/' else [{'@type':'ListItem','position':3,'name':title,'item':url}])}]}
    content = f'''<!DOCTYPE html>
{MARKER}
<html lang="en"><head>{analytics}
<meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"/>
<title>{escape(title)} | BrainiLab</title><meta name="description" content="{escape(description, quote=True)}"/>
<meta name="google-adsense-account" content="ca-pub-5613536700850101"/>
<meta name="robots" content="index,follow"/><link rel="canonical" href="{url}"/>
<meta property="og:type" content="{'website' if path == '/learn/' else 'article'}"/><meta property="og:title" content="{escape(title, quote=True)}"/>
<meta property="og:description" content="{escape(description, quote=True)}"/><meta property="og:url" content="{url}"/>
<meta property="og:image" content="{BASE}{escape(cover['src'])}"/><meta property="og:image:alt" content="{escape(cover['alt'], quote=True)}"/>
<meta name="twitter:card" content="summary_large_image"/>
<link rel="icon" href="/assets/brand/iso-multicolor.png"/>
<link rel="stylesheet" href="/assets/css/site.css?v=41.17.0"/><link rel="stylesheet" href="/assets/css/mobile.css?v=41.8.3"/>
<link rel="stylesheet" href="/assets/css/editorial.css?v=41.17.0"/>
<script defer src="/assets/js/shell.bundle.js?v=41.17.0"></script>
{'<script defer src="/assets/js/learn-library.js?v=41.17.0"></script>' if path == '/learn/' else ''}
<script type="application/ld+json">{json.dumps(graph, ensure_ascii=False).replace('</', '<\\/')}</script>
</head><body class="editorial-page"><a class="editorial-skip" href="#main-content">Skip to main content</a>
{header}<main id="main-content">{body}</main>{footer}<div class="toast" role="status"></div></body></html>'''
    target = ROOT/path.strip('/')/'index.html'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding='utf-8')

topics = sorted({a['topic'] for a in articles})
latest_by_topic={}
for a in sorted(articles,key=lambda a:a.get("publishedAt",""),reverse=True):
    latest_by_topic.setdefault(a["topic"],a["slug"])
library_parts=[]
for i,a in enumerate(articles):
    latest=latest_by_topic[a['topic']]==a['slug']
    library_parts.append(card(a,i<3).replace('class="learn-card"', 'class="learn-card" data-latest-topic' if latest else 'class="learn-card" hidden', 1))
library=''.join(library_parts)
page('/learn/', 'Learn: curious questions, clear answers', 'Explore science, geography, history, numbers and word puzzles. Short reads with worked examples, a quick question and a related game.', f'''
<div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span aria-current="page">Learn</span></nav>
<header class="learn-hero"><div><h1>A little more to discover.</h1><p>Curious questions, clear answers and a few things to try.</p></div>
<label class="learn-search" hidden>Find an article<input type="search" id="learn-search" placeholder="Try Moon, flags, numbers…" autocomplete="off" aria-controls="learn-articles"/></label></header>
<nav class="topic-nav" aria-label="Filter articles by topic" hidden><button type="button" data-topic-filter="__latest" aria-pressed="true">Latest by topic</button><button type="button" data-topic-filter="" aria-pressed="false">All articles</button>{''.join(f'<button type="button" data-topic-filter="{escape(t,quote=True)}" aria-pressed="false">{escape(t)}</button>' for t in topics)}</nav>
<p class="learn-count" role="status" aria-live="polite" id="learn-count">{len(topics)} articles · latest in each topic</p>
<noscript><style>.library-grid .learn-card[hidden]{{display:flex!important}}</style><p>All articles are shown below. Enable JavaScript to use search and topic filters.</p></noscript><div class="learn-grid library-grid" id="learn-articles">{library}</div>
<div class="learn-empty" hidden><h2>No articles found</h2><p>Try another word or browse all topics.</p><button type="button" data-clear-filters>Show all articles</button></div>
<p class="learn-footer-link">In the mood to play? <a href="/games/">Browse the games →</a></p></div>''', {'@type':'CollectionPage','name':'BrainiLab Learn','url':BASE+'/learn/','description':'Short reads on science, geography, history and puzzles','hasPart':[{'@type':'Article','headline':a['title'],'url':BASE+'/learn/'+a['slug']+'/','image':BASE+a['cover']['src']} for a in articles]})

for a in articles:
    toc = ''.join(f'<li><a href="#{s["id"]}">{escape(s["title"])}</a></li>' for s in a['sections'])
    sections = ''.join(f'<section id="{s["id"]}"><h2>{escape(s["title"])}</h2>{s["html"]}</section>' for s in a['sections'])
    related = ''.join(card(by_slug[slug]) for slug in a.get('related', []) if slug in by_slug)
    sources = ''.join(f'<li><a href="{escape(s["url"], quote=True)}">{escape(s["name"])}</a></li>' for s in a['sources'])
    body = f'''<div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><a href="/learn/">Learn</a><span aria-hidden="true">/</span><span aria-current="page">{escape(a['topic'])}</span></nav>
    <header class="article-header"><p class="eyebrow">{escape(a['topic'])} · {a['minutes']} min read</p><h1>{escape(a['title'])}</h1><p>{escape(a['description'])}</p></header>
    <div class="article-layout"><aside class="article-sidebar"><details><summary>In this article</summary><nav aria-label="In this article"><ol>{toc}</ol></nav></details><a class="sidebar-game" href="{escape(a['game']['url'], quote=True)}">Related game<strong>{escape(a['game']['name'])} →</strong></a></aside>
    <article class="article-body"><figure class="article-cover"><img src="{escape(a['cover']['src'])}" alt="{escape(a['cover']['alt'],quote=True)}" width="960" height="640" fetchpriority="high"/><figcaption>{escape(a['cover']['credit'])}</figcaption></figure>{sections}<section id="sources"><h2>Sources &amp; further reading</h2><ul>{sources}</ul></section>
    <aside class="article-practice"><h2>Fancy a round?</h2><p>{escape(a['practice'])}</p><a class="btn" href="{escape(a['game']['url'], quote=True)}">Play {escape(a['game']['name'])} →</a><a class="article-hub-link" href="{escape(a['hub']['url'], quote=True)}">Explore {escape(a['hub']['name'])}</a></aside></article></div>
    <section class="learn-related"><div class="section-heading"><h2>Keep exploring</h2><a href="/learn/">All guides →</a></div><div class="learn-grid">{related}</div></section></div>'''
    page('/learn/'+a['slug']+'/', a['title'], a['description'], body, {'@type':'Article','headline':a['title'],'description':a['description'],'url':BASE+'/learn/'+a['slug']+'/','image':BASE+a['cover']['src'],'inLanguage':'en','publisher':{'@type':'Organization','name':'BrainiLab','url':BASE+'/'},'mainEntityOfPage':BASE+'/learn/'+a['slug']+'/'},a['cover'])

# Only files with our exact generated marker can be removed when unpublishing.
for p in (ROOT/'learn').glob('*/index.html'):
    if p.parent.name not in by_slug and MARKER in p.read_text(encoding='utf-8'):
        p.unlink()

ns = 'http://www.sitemaps.org/schemas/sitemap/0.9'
ET.register_namespace('', ns)
tree = ET.parse(ROOT/'sitemap.xml')
for entry in list(tree.getroot()):
    loc = entry.find('{'+ns+'}loc')
    if loc is not None and loc.text.startswith(BASE+'/learn/'):
        tree.getroot().remove(entry)
for path in ['/learn/'] + ['/learn/'+a['slug']+'/' for a in articles]:
    entry = ET.SubElement(tree.getroot(), '{'+ns+'}url')
    ET.SubElement(entry, '{'+ns+'}loc').text = BASE+path
ET.indent(tree, space='  ')
tree.write(ROOT/'sitemap.xml', encoding='utf-8', xml_declaration=True)

if '<!-- learn-preview:start -->' in home:
    a = sorted(articles, key=lambda a: (-datetime.fromisoformat(a['publishedAt'].replace('Z','+00:00')).timestamp(),a['slug']))[0]
    position=a['cover'].get('position',20 if 'moon' in a['slug'] else 45)
    preview = f'''<!-- learn-preview:start --><a class="home-article" href="/learn/{a['slug']}/"><img src="{escape(a['cover']['src'].replace('.webp','-small.webp'))}" alt="" style="object-position:center {position}%" width="480" height="320" decoding="async"/><span class="home-article-copy"><span class="home-article-label">Latest in Learn · {a['minutes']} min read</span><strong>{escape(a['title'])}</strong><span class="home-article-action">Read the article →</span></span></a><!-- learn-preview:end -->'''
    home = re.sub(r'<!-- learn-preview:start -->.*?<!-- learn-preview:end -->', lambda _: preview, home, flags=re.S)
    (ROOT/'index.html').write_text(home, encoding='utf-8')
print(f'Built Learn library and {len(articles)} published articles; drafts excluded.')
