"""Build the static Learn library from reviewed content/articles/*.json files."""
from pathlib import Path
from html import escape
from urllib.parse import urlsplit
import json
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://brainilabgames.com'
MARKER = '<!-- Generated by tools/build-editorial.py; edit content/articles instead. -->'
home = (ROOT/'index.html').read_text(encoding='utf-8')
header = re.search(r'<header\b.*?</header>', home, re.S).group()
header = re.sub(r'(?<![\w/])((?:href|src|srcset)=")(?!(?:/|https:|#))', r'\1/', header)
header = header.replace('<a href="/learn/">', '<a href="/learn/" aria-current="page">')
footer = re.search(r'<footer\b.*?</footer>', home, re.S).group()
footer = re.sub(r'(?<![\w/])((?:href|src|srcset)=")(?!(?:/|https:|#))', r'\1/', footer)
analytics = home.split('<head>', 1)[1].split('<meta charset', 1)[0]

all_articles = [json.loads(p.read_text(encoding='utf-8')) for p in sorted((ROOT/'content/articles').glob('*.json'))]
slugs = set()
for a in all_articles:
    assert re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', a['slug']), 'Invalid slug'
    assert a['slug'] not in slugs, 'Duplicate slug'
    slugs.add(a['slug'])
    assert a['status'] in ('draft', 'published'), 'Invalid status'
articles = [a for a in all_articles if a['status'] == 'published']
by_slug = {a['slug']: a for a in articles}
for a in articles:
    for key in ('title', 'description', 'topic', 'sections', 'sources', 'game', 'hub'):
        assert a.get(key), f"Missing {key} in {a['slug']}"
    ids = [section['id'] for section in a['sections']]
    assert len(ids) == len(set(ids)) and all(re.fullmatch(r'[a-z0-9-]+', i) for i in ids)
    for link in (a['game'], a['hub']):
        target = ROOT/urlsplit(link['url']).path.strip('/')/'index.html'
        assert target.is_file(), f'Missing destination: {target}'
    words = len(re.sub('<[^>]+>', ' ', ' '.join(s['html'] for s in a['sections'])).split())
    a['minutes'] = max(1, round(words/200))

def card(a):
    return f'''<article class="learn-card">
      <div class="learn-card-art"><img src="/assets/icons/categories/{escape(a['icon'])}.svg" alt="" width="80" height="80" loading="lazy"/></div>
      <div class="learn-card-copy"><p class="eyebrow">{escape(a['topic'])} <span>· {a['minutes']} min read</span></p>
      <h3><a href="/learn/{a['slug']}/">{escape(a['title'])}</a></h3>
      <p>{escape(a['description'])}</p><span class="learn-card-label" aria-hidden="true">Read the guide ↗</span></div>
    </article>'''

def page(path, title, description, body, schema):
    url = BASE + path
    graph = {'@context': 'https://schema.org', '@graph': [schema, {'@type':'BreadcrumbList','itemListElement':[
        {'@type':'ListItem','position':1,'name':'Home','item':BASE+'/'},
        {'@type':'ListItem','position':2,'name':'Learn','item':BASE+'/learn/'}
    ] + ([] if path == '/learn/' else [{'@type':'ListItem','position':3,'name':title,'item':url}])}]}
    content = f'''<!DOCTYPE html>
{MARKER}
<html lang="en"><head>{analytics}
<meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"/>
<title>{escape(title)} | BrainiLab</title><meta name="description" content="{escape(description, quote=True)}"/>
<meta name="robots" content="index,follow"/><link rel="canonical" href="{url}"/>
<meta property="og:type" content="{'website' if path == '/learn/' else 'article'}"/><meta property="og:title" content="{escape(title, quote=True)}"/>
<meta property="og:description" content="{escape(description, quote=True)}"/><meta property="og:url" content="{url}"/>
<meta property="og:image" content="{BASE}/assets/brand/og-card.png"/><meta property="og:image:alt" content="BrainiLab quiz and brain games"/>
<meta name="twitter:card" content="summary_large_image"/>
<link rel="icon" href="/assets/brand/iso-multicolor.png"/>
<link rel="stylesheet" href="/assets/css/site.css?v=41.11.0"/><link rel="stylesheet" href="/assets/css/mobile.css?v=41.8.3"/>
<link rel="stylesheet" href="/assets/css/editorial.css?v=41.12.0"/>
<script defer src="/assets/js/shell.bundle.js?v=41.12.0"></script>
<script type="application/ld+json">{json.dumps(graph, ensure_ascii=False).replace('</', '<\\/')}</script>
</head><body class="editorial-page"><a class="editorial-skip" href="#main-content">Skip to main content</a>
{header}<main id="main-content">{body}</main>{footer}<div class="toast" role="status"></div></body></html>'''
    target = ROOT/path.strip('/')/'index.html'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding='utf-8')

topics = sorted({a['topic'] for a in articles})
topic_id = lambda t: t.lower().replace(' ', '-')
library = ''.join(f'''<section class="learn-topic" id="{topic_id(t)}" aria-labelledby="{topic_id(t)}-title"><div class="section-heading"><h2 id="{topic_id(t)}-title">{escape(t)}</h2><span>{sum(a['topic']==t for a in articles)} guide{'s' if sum(a['topic']==t for a in articles)!=1 else ''}</span></div><div class="learn-grid">{''.join(card(a) for a in articles if a['topic']==t)}</div></section>''' for t in topics)
page('/learn/', 'Learn something. Put it into play.', 'Practical guides to geography, quiz practice and BrainiLab games. Find a topic, understand the idea and try a related challenge.', f'''
<div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span aria-current="page">Learn</span></nav>
<header class="learn-hero"><p class="eyebrow">THE BRA IN YOUR BRAIN BREAK</p><h1>Learn something.<br/><span>Put it into play.</span></h1><p>Clear explanations, useful examples and a game to try next.<br/>A little reading can give your next challenge a new direction.</p>
<nav class="topic-nav" aria-label="Guide topics">{''.join(f'<a href="#{topic_id(t)}">{escape(t)}</a>' for t in topics)}</nav></header>
{library}<aside class="learn-next"><div><p class="eyebrow">READY WHEN YOU ARE</p><h2>More of a learn-by-doing person?</h2><p>Pick a free game and follow your curiosity.</p></div><a class="btn-secondary" href="/games/">Explore the games →</a></aside></div>'''.replace('THE BRA IN YOUR BRAIN BREAK','A LITTLE CURIOSITY GOES A LONG WAY'), {'@type':'CollectionPage','name':'BrainiLab Learn','url':BASE+'/learn/','description':'Practical guides connected to BrainiLab games','hasPart':[{'@type':'Article','headline':a['title'],'url':BASE+'/learn/'+a['slug']+'/'} for a in articles]})

for a in articles:
    toc = ''.join(f'<li><a href="#{s["id"]}">{escape(s["title"])}</a></li>' for s in a['sections'])
    sections = ''.join(f'<section id="{s["id"]}"><h2>{escape(s["title"])}</h2>{s["html"]}</section>' for s in a['sections'])
    related = ''.join(card(by_slug[slug]) for slug in a.get('related', []) if slug in by_slug)
    sources = ''.join(f'<li><a href="{escape(s["url"], quote=True)}">{escape(s["name"])}</a></li>' for s in a['sources'])
    body = f'''<div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><a href="/learn/">Learn</a><span aria-hidden="true">/</span><span aria-current="page">{escape(a['topic'])}</span></nav>
    <header class="article-header"><p class="eyebrow">{escape(a['topic'])} · {a['minutes']} min read</p><h1>{escape(a['title'])}</h1><p>{escape(a['description'])}</p></header>
    <div class="article-layout"><aside class="article-sidebar"><nav aria-label="In this guide"><p class="eyebrow">IN THIS GUIDE</p><ol>{toc}</ol></nav><a class="sidebar-game" href="{escape(a['game']['url'], quote=True)}">Put it into practice →<strong>{escape(a['game']['name'])}</strong></a></aside>
    <article class="article-body">{sections}<section id="sources"><h2>Sources &amp; further reading</h2><ul>{sources}</ul></section>
    <aside class="article-practice"><p class="eyebrow">YOUR NEXT STEP</p><h2>Turn the idea into a little practice.</h2><p>Try a round, review the result and choose one thing to come back to.</p><a class="btn" href="{escape(a['game']['url'], quote=True)}">Play {escape(a['game']['name'])} →</a><a class="article-hub-link" href="{escape(a['hub']['url'], quote=True)}">Explore {escape(a['hub']['name'])}</a></aside></article></div>
    <section class="learn-related"><div class="section-heading"><h2>Keep exploring</h2><a href="/learn/">All guides →</a></div><div class="learn-grid">{related}</div></section></div>'''
    page('/learn/'+a['slug']+'/', a['title'], a['description'], body, {'@type':'Article','headline':a['title'],'description':a['description'],'url':BASE+'/learn/'+a['slug']+'/','inLanguage':'en','publisher':{'@type':'Organization','name':'BrainiLab','url':BASE+'/'},'mainEntityOfPage':BASE+'/learn/'+a['slug']+'/'})

# Only files with our exact generated marker can be removed when unpublishing.
for p in (ROOT/'learn').glob('*/index.html'):
    if p.parent.name not in by_slug and MARKER in p.read_text(encoding='utf-8'):
        p.unlink()

ns = 'http://www.sitemaps.org/schemas/sitemap/0.9'
ET.register_namespace('', ns)
tree = ET.parse(ROOT/'sitemap.xml')
for entry in list(tree.getroot()):
    loc = entry.find('{'+ns+'}loc')
    if loc is not None and loc.text.startswith(BASE+'/learn/'):
        tree.getroot().remove(entry)
for path in ['/learn/'] + ['/learn/'+a['slug']+'/' for a in articles]:
    entry = ET.SubElement(tree.getroot(), '{'+ns+'}url')
    ET.SubElement(entry, '{'+ns+'}loc').text = BASE+path
ET.indent(tree, space='  ')
tree.write(ROOT/'sitemap.xml', encoding='utf-8', xml_declaration=True)

if '<!-- learn-preview:start -->' in home:
    preview = '<!-- learn-preview:start -->' + ''.join(card(a) for a in articles[:2]) + '<!-- learn-preview:end -->'
    home = re.sub(r'<!-- learn-preview:start -->.*?<!-- learn-preview:end -->', lambda _: preview, home, flags=re.S)
    (ROOT/'index.html').write_text(home, encoding='utf-8')
print(f'Built Learn library and {len(articles)} published articles; drafts excluded.')
